Update Function Bar
ebf/ebf-design-system pull request #123
Opened 2022-05-11 12:57 UTC by zeljadin

Update:
- Height (y-paddings)
- Component classes update
- Add custom variables
- Responsive

2022-05-12 15:27 UTC, moysa requested changes

2022-05-12 15:27 UTC, moysa commented on app/styles/ebf-design-system/themes/telekom/components/_footer.scss
> +  @extend .container-fluid;
you could use `@include make-container()` instead, to avoid using `@extend`

2022-05-12 15:30 UTC, zeljadin commented on app/styles/ebf-design-system/themes/telekom/components/_footer.scss
> +  @extend .container-fluid;
yeah, but there's no mixin for @include make-container-**fluid**()

2022-05-18 10:19 UTC, moysa commented on app/styles/ebf-design-system/themes/telekom/components/_footer.scss
> +  @extend .container-fluid;
`make-container()` is for the fluid container

2022-05-27 11:08 UTC, merged