Page Progress component
ebf/ebf-design-system pull request #124
Opened 2022-05-11 14:02 UTC by vladaspasic

Created a `PageProgress` component that would replace the `n-progress` one.

2022-05-11 17:12 UTC, moysa requested changes

2022-05-11 17:12 UTC, moysa commented on tests/dummy/app/templates/docs.hbs
> +<PageProgress />
I think that there should be a dedicated page for this component rather then globally present. That way there would be an explicit example and documentation for the use of this component.

2022-05-12 11:08 UTC, vladaspasic commented on app/styles/ebf-design-system/themes/telekom/components/_page-progress.scss
> +    position: fixed;
The `NProgress` that was previously used was fixed to the top. The nature of this component is that is directly tied to the `ajax` service, any request would trigger the progress animation. There is no way currently to have this progress per request, at least for now. Considering this, the component should only be *rendered once per page*, otherwise it is redundant

2022-05-12 13:06 UTC, moysa approved these changes

2022-05-12 13:26 UTC, merged