EBF-265: Add a `<Breadcrumbbar>` component
ebf/ebf-design-system pull request #37
Opened 2021-11-02 12:50 UTC by obyknovenius

2021-11-02 13:00 UTC, obyknovenius commented
The current implementation has the following issues.
1. Every nested `<a>` element must have `data-text` attribute to prevent the "jumping" effect on hover.
2. When using a static text as a segment, it must be manually set as `@active`.
3. When using the `<LinkTo>` component, Ember automatically adds the `active` attribute, which makes the corresponding segment look like it is the current page.

2021-11-02 16:43 UTC, moysa commented
First off, I would suggest using the name `Breadcrumb`, I don't think that the `bar` suffix is necessary.

Concerning the three issues, I would use `LinkTo` as the default item component. You can set the `active` attribute of the `LinkTo` component to control it's state. So I would suggest the following:
```
<Breadcrumb as |bar|>
  <bar.item @route="docs" @label="Docs" />
  <bar.item @route="docs.breadcrumbs" @label="Breadcrumbs" @active={{true}}/>
</Breadcrumb>
```
and the item would render the `LinkTo` component. If an item has a block, then render what ever is in the block. This way we will have enough control while allowing for flexibility.

2021-11-03 13:12 UTC, moysa requested changes

2021-11-03 13:12 UTC, moysa commented on tests/dummy/app/components/docs/breadcrumb/index.hbs
> +      <bar.item @active={{true}}>Data</bar.item>
Set this example as an active LinkTo. ie: `<bar.item @route="docs.breadcrumbs" @label="Docs" @active={{true}} />`

Example of block content can be in a separate Breadcrumb.

2021-11-04 10:14 UTC, obyknovenius commented on tests/dummy/app/components/docs/breadcrumb/index.hbs
> +      <bar.item @active={{true}}>Data</bar.item>
Like this?
```hbs
<Breadcrumb as |bar|>
  <bar.item @route="docs" @label="Docs" />
  <bar.item @route="docs.breadcrumbs" @label="Breadcrumbs" @active={{true}} />
</Breadcrumb>
```

```hbs
<Breadcrumb as |bar|>
  <bar.item>
    <a href="#" data-text="Home">Home</a>
  </bar.item>
  <bar.item>
    <a href="#" data-text="Library">Library</a>
  </bar.item>
  <bar.item @active={{true}}>
    Data
  </bar.item>
</Breadcrumb>
```

2021-11-04 10:18 UTC, moysa commented on tests/dummy/app/components/docs/breadcrumb/index.hbs
> +      <bar.item @active={{true}}>Data</bar.item>
Yes

2021-11-04 11:02 UTC, moysa approved these changes

2021-11-04 14:23 UTC, moysa approved these changes

2021-11-04 14:45 UTC, merged