EBF-482: Fix <Notifications> dropdown alignment in <Navbar>
ebf/ebf-design-system pull request #59
Opened 2022-01-14 11:42 UTC by obyknovenius

ember-bootstrap docs says: If you need to use dropdowns in a nav, use the `bs-nav.dropdown` contextual component rather than a standalone `dropdown` to ensure the correct styling regardless of your Bootstrap version.

Since we always use <Notifications> component inside <TopNavigation>'s navbar, we now passing it as a parameter.

2022-01-15 00:44 UTC, vladaspasic approved these changes

2022-01-17 12:12 UTC, moysa requested changes

2022-01-17 12:12 UTC, moysa commented on addon/components/notifications/index.hbs
> +{{#with @nav as |nav|}}
Setting `inNav` flag to `true` would do the desired effect without the need of passing in the `nav` component

2022-01-17 15:19 UTC, moysa approved these changes

2022-01-17 15:25 UTC, merged